# The duration of each player's turn in seconds.
# Default: 600 (10 minutes)
turn-duration: 600

# The number of consecutive player deaths allowed before the world ends.
# Set to 1 for a classic "first death ends the game" hardcore experience.
# Default: 2
max-consecutive-deaths: 2


# The number of turns a player skips after dying (if the game doesn't end).
# Default: 2
death-penalty-skips: 2


# If true, the game will pause if only one player is online.
# Default: true
wait-for-more-players: true


# The message displayed on the action bar when waiting for more players.
waiting-message: "&cWaiting for more players to join the relay..."


# --- UI Customization ---

# Action bar message format for spectators.
# Placeholders: {health}, {hunger}, {time}, {next_player}
spectator-message: "&cHP: &f{health} &c| Hunger: &f{hunger} &c| Time: &f{time} &c| Next: &f{next_player}"


# Action bar message for the active player during the final seconds.
# Placeholder: {time}
active-player-countdown-message: "&4! Switching to {next_player} in {time} !"